== GitHub Stats
This is a test app to showcase usage of GitHub API with an Angular front end.

=== Prerequisites
JDK, Gradle and finally get ready to witness awesomeness of Angular :)

=== Steps

 - Clone app

 - Run below command at project root

    ./gradlew bootRun

 - Open

    localhost:8080

=== How to Use?
 - Once app starts and `localhost:8080` is open, search for an organization name:

  Example: Netfli, Netflix, Micro, Microsoft

 - After getting list of orgs browse them to see all of their repositories.
 - Select "Recent Commits" under each repo to see latest commits. Number of commits is defaulted to 2.


=== Trivial Test Cases
Search for an org name. Get a list of orgs. Open accordion and click "See Repository":

1. A warning message is shown if no repo is found for the org.
2. A new section with repos of the org will be shown. Select popularity order from "Popular By" dropdown and check order of repos is altered accordingly.
3. Now click on "Recent commits" on any repo. Another section will be opened to show 2(default) recent commits to the repo.
4. Now click on "Recent commits" on any repo. Another section will be opened to show 2(default) recent commits to the repo. Change "Limit To" 5/10 to see recent 5/10 commits displayed.

=== Running Unit tests

    npm install -g karma --save-dev
    npm install -g karma-jasmine --save-dev
    npm install -g karma-phantomjs-launcher --save-dev

    karma start spec.conf.js

